-- Text-only accessibility edits to active Career Test questions.
-- Preserves question UUIDs, dimensions, ordering, options, scoring, and attempt history.
-- Guarded by exact old/new text; a mismatch rolls back the entire transaction.
BEGIN;
DO $question_wording$
DECLARE updated_rows integer;
BEGIN
  UPDATE public.questions AS q
  SET question_text = changes.new_text
  FROM (VALUES
    ('1080987d-0e8f-4444-a754-7c2cf3a9ca98'::uuid, 'I enjoy contributing to open-source software projects.', 'I would enjoy learning how people share and improve software that anyone can use.'),
    ('4c16499b-50ca-4b2e-aa75-961cf6c2e27d'::uuid, 'I am interested in understanding how software is tested and maintained.', 'I would enjoy learning how to check software for mistakes and keep it working well.'),
    ('77032736-f77c-4fbf-b249-494e4ba9aef2'::uuid, 'I enjoy spending my free time coding or building software projects.', 'I would enjoy creating a small program or digital tool to solve a problem.'),
    ('aae7b57e-e794-4358-8b52-d0da8e44e830'::uuid, 'I prefer tasks that involve implementing new features in existing software.', 'I would enjoy adding a useful new feature to an app that already exists.'),
    ('9de062ee-d63f-44c1-b5d4-10e47d1a8ffa'::uuid, 'I find satisfaction in creating software that others can use.', 'I would enjoy creating software that makes a useful task easier for someone else.'),
    ('b3d66623-2180-4d7a-bc52-a028e3d94ebe'::uuid, 'I am interested in learning about software design patterns and architecture.', 'I am curious about how software can be organized so larger programs are easier to understand.'),
    ('b783bacb-89b2-4c03-8e3f-99d90b54184d'::uuid, 'I enjoy working on the frontend/client-side of applications.', 'I would enjoy designing the parts of an app that people see and use.'),
    ('c09f631d-1878-444f-a564-cf4a001a78fb'::uuid, 'I prefer working on problems that involve writing and debugging code.', 'I would enjoy writing instructions for a computer and figuring out why they do not work.'),
    ('c3a6ab24-c792-4643-a456-fff3b4620e4a'::uuid, 'I prefer working on projects that have clear technical requirements.', 'I like having clear goals and steps when I work on a software project.'),
    ('c6760863-652c-4c14-846a-7898478850cf'::uuid, 'I find it rewarding to optimize code for better performance.', 'I enjoy finding ways to make a program run faster.'),
    ('c8b96608-a840-4323-9e44-68b3f5a86aab'::uuid, 'I am interested in the process of deploying software to production.', 'I am curious about how an app is prepared for people to use online.'),
    ('d4b32dba-f1f7-4000-b86d-03d0f89a5591'::uuid, 'I enjoy collaborating with others to build large software systems.', 'I would enjoy working with others to build software that solves a larger problem.'),
    ('e3d66120-b12e-4bb8-97bb-c8906e0d6e88'::uuid, 'I find satisfaction in solving complex algorithmic challenges.', 'I enjoy breaking a difficult problem into clear steps a computer can follow.'),
    ('f8c306e8-57e3-43c6-8098-7500298248d3'::uuid, 'I prefer working on the backend/server-side of applications.', 'I am curious about what happens behind the scenes when an app processes information.'),
    ('4fb712f0-ce76-460c-a131-1e75ea80a40e'::uuid, 'I prefer making decisions based on data and analysis rather than intuition.', 'I like checking information and evidence before deciding what it might mean.'),
    ('fc51c4a0-4238-4a7a-ad90-3974a5fc119c'::uuid, 'I enjoy working with data to uncover patterns and insights.', 'I enjoy looking at information and spotting patterns that help answer questions.'),
    ('9eaa57e3-6de0-4492-8778-f469ed94cafa'::uuid, 'I find satisfaction in creating visualizations to explain data.', 'I enjoy using charts to make information easier to understand.'),
    ('aaa2ac21-f4b2-4d2d-b619-f390852eef10'::uuid, 'I am interested in learning statistical methods for data analysis.', 'I am curious about using math to learn what a set of information can tell us.'),
    ('1ec70d3e-17e9-4f13-a77e-85971cb17502'::uuid, 'I enjoy cleaning and preparing data for analysis.', 'I would enjoy organizing information so it is accurate and ready to use.'),
    ('3287b265-5076-4700-9a89-5fcc1b9ffd9a'::uuid, 'I find it rewarding to build predictive models from data.', 'I am curious about using past examples to estimate what could happen next.'),
    ('666fce2f-6177-4889-b652-3d29c655a3cf'::uuid, 'I am interested in learning about data mining techniques.', 'I am curious about how a computer can sort many records into groups with shared features.'),
    ('3472bdbc-2402-4103-981c-e51cefd51912'::uuid, 'I enjoy explaining data-driven insights to non-technical audiences.', 'I enjoy explaining what information shows in clear language.'),
    ('37b50461-f87c-434c-8924-0796a6c51784'::uuid, 'I prefer tasks that involve querying databases to extract information.', 'I am interested in asking stored information a question and finding the matching answers.'),
    ('098abc89-b340-4b96-96f1-90d18576e4b4'::uuid, 'I find satisfaction in identifying trends in large datasets.', 'I enjoy noticing how numbers or events change across many examples.'),
    ('8d02e84d-339e-4f0a-b56b-0ba28ea84869'::uuid, 'I am interested in learning about big data technologies.', 'I am curious about tools used to work with very large amounts of information.'),
    ('72d87cbd-66d3-434f-9d68-2470c9f864dc'::uuid, 'I enjoy working with spreadsheets and data analysis tools.', 'I would enjoy using tables and digital tools to organize and understand information.'),
    ('efb965cd-0b47-4dbb-a878-69ecd3610100'::uuid, 'I enjoy learning about machine learning algorithms and how they work.', 'I enjoy learning how computers find patterns in examples and use them to make predictions.'),
    ('1f6e8d58-9a04-4f17-88da-563cd004b81f'::uuid, 'I prefer working on problems that involve creating intelligent systems.', 'I would enjoy creating software that chooses a helpful response based on the information it receives.'),
    ('290fd553-9c3e-400f-95e3-7f3f5ab88f78'::uuid, 'I find satisfaction in training models to recognize patterns in data.', 'I am curious about teaching a computer to notice patterns from examples.'),
    ('49e87a53-b08c-4989-b9c1-51afbf4eeb1c'::uuid, 'I am interested in learning about reinforcement learning.', 'I am curious about how a computer might improve by trying actions and learning from feedback.'),
    ('510b228b-c88a-48fc-8828-910dd5cea251'::uuid, 'I find it rewarding to evaluate the performance of AI models.', 'I enjoy checking how often an AI tool gives a useful answer across many examples.'),
    ('7cde9aad-2f17-4294-96d9-05bdcd6cd7b1'::uuid, 'I prefer tasks that involve natural language processing or computer vision.', 'I am interested in ways computers work with everyday language or recognize things in pictures.'),
    ('0a51d5a5-ce38-4d46-b631-16cb5910d04f'::uuid, 'I prefer learning about the mathematical foundations of AI.', 'I am interested in learning the math ideas that help explain how AI works.'),
    ('b8dfafd3-2fe4-4774-8504-097e6e4ca0c0'::uuid, 'I enjoy experimenting with AI tools and frameworks.', 'I enjoy trying AI tools to see what useful tasks they can help with.'),
    ('03efc932-afc4-4f32-9261-6cc7a1d3ebf7'::uuid, 'I find satisfaction in debugging and improving AI models.', 'I enjoy figuring out why an AI tool gave an incorrect answer and how it could improve.'),
    ('fcceefe6-e742-4056-a4eb-2fc6693cab92'::uuid, 'I enjoy reading research papers about advancements in AI.', 'I like reading clear explanations of new ideas in AI.'),
    ('9b33b9b8-3a95-4089-ae46-e411602f40bc'::uuid, 'I am interested in understanding how neural networks function.', 'I am curious about how AI systems use connected steps to recognize patterns.'),
    ('0daf561f-5541-4acf-831a-6640755d5d6e'::uuid, 'I am interested in learning about distributed systems and microservices.', 'I am curious about how large digital services can be split into smaller parts that work together.'),
    ('1dad059e-e5c9-42e2-bd34-c5932eaae7d9'::uuid, 'I find it rewarding to monitor system performance and troubleshoot issues.', 'I enjoy finding why a computer service is slow or not working as expected.'),
    ('2754dfc4-835a-40d8-848b-28602af6c037'::uuid, 'I prefer tasks that involve setting up and maintaining databases.', 'I would enjoy organizing information so an app can store and find it reliably.'),
    ('505d0913-f847-4386-863b-8b49f4773c3a'::uuid, 'I am interested in learning about virtualization technologies.', 'I am curious how one physical computer can safely run several separate computing environments.'),
    ('6804b19c-d543-4cd9-a518-e9502a534dc2'::uuid, 'I prefer tasks that involve designing system architecture.', 'I would enjoy planning how parts of a computer system connect and work together.'),
    ('76af079c-6488-447d-9dc5-578b8e49ef11'::uuid, 'I prefer working on problems that involve configuring servers and networks.', 'I am curious how computers are set up to share information and services.'),
    ('865236df-d004-4d48-8eaf-553e995457ad'::uuid, 'I find satisfaction in ensuring systems are reliable and scalable.', 'I enjoy making a digital service dependable as more people use it.'),
    ('868b3155-e6d7-477e-a628-f0fb97c7ec10'::uuid, 'I am interested in learning about containerization and orchestration (e.g., Docker, Kubernetes).', 'I am interested in tools that help software run consistently on different computers and manage many running copies.'),
    ('8c0e6a4f-bc99-41ac-8afa-ed4de7968fb2'::uuid, 'I find satisfaction in optimizing system resource usage.', 'I enjoy finding ways to use a computer’s memory and processing time efficiently.'),
    ('9d708f32-7692-452a-977a-0c5d2e2aedbb'::uuid, 'I am interested in learning about cloud computing platforms.', 'I am interested in running apps and storing information using computers accessed over the internet.'),
    ('b02f8f2a-86e6-4717-b1c1-e07477aa4eb8'::uuid, 'I prefer working on problems that involve network security and firewalls.', 'I like learning how connected devices can be protected from unwanted access.'),
    ('c8d153c2-be43-4ff9-b5e6-278bd7259cb7'::uuid, 'I enjoy working with command-line interfaces and system administration tools.', 'I enjoy giving a computer instructions by typing commands instead of using menus.'),
    ('c97429f0-d666-4735-aaba-f1cc83a0056f'::uuid, 'I enjoy learning about operating systems and their inner workings.', 'I am curious how a computer manages apps, files, memory, and devices.'),
    ('f771b11e-a5c9-481f-a645-02a56998a44b'::uuid, 'I enjoy scripting and automating repetitive system tasks.', 'I enjoy finding ways for a computer to handle repeated tasks automatically.'),
    ('01b19634-5583-4296-9410-8c3e27ed1647'::uuid, 'I find satisfaction in implementing security best practices in software.', 'I would enjoy learning how to protect accounts and information when software is created.'),
    ('17ffd089-4e24-4635-90e9-b1faea27abef'::uuid, 'I prefer working on problems that involve secure software development lifecycle.', 'I am curious how safety checks can be included from the start through every stage of building software.'),
    ('1a32ecea-d070-4b61-be31-58228c9bedbf'::uuid, 'I am interested in learning about security compliance and regulations.', 'I am interested in the rules that help organizations handle personal information safely and fairly.'),
    ('328e55c9-95c4-4472-8f20-e456d73deefc'::uuid, 'I enjoy staying updated on the latest security threats and how to mitigate them.', 'I enjoy thinking about how technology could fail or be misused and how to make it safer.'),
    ('42c50def-a2a9-4e8f-b600-c7a7d6990226'::uuid, 'I prefer learning about encryption and secure communication protocols.', 'I am curious how a message can be scrambled so only the intended people can read it.'),
    ('5b08fe69-ae8b-4c04-a585-f181b7427029'::uuid, 'I enjoy learning about incident response and digital forensics.', 'I would enjoy finding out what happened after a digital security problem and helping people recover.'),
    ('5d169f60-417a-42c0-ae2f-9cea0c476020'::uuid, 'I prefer tasks that involve implementing authentication and authorization systems.', 'I am interested in how apps check who someone is and decide what that person can do.'),
    ('7a3e8c51-a8bc-4073-ac59-3d2f6fe853d1'::uuid, 'I enjoy learning about network security and intrusion detection systems.', 'I enjoy learning how computers can notice unusual activity across a network.'),
    ('bbf46ec0-52f7-4b0d-b6b9-7e22ea3d2db2'::uuid, 'I find it rewarding to conduct security audits and penetration testing.', 'I would enjoy safely checking a system for weak spots before someone else finds them.'),
    ('c81090e6-e608-4f10-9931-41d53722c652'::uuid, 'I am interested in learning about secure coding practices.', 'I am interested in writing software in ways that avoid common security mistakes.'),
    ('d4f70382-1af0-418f-8daa-a107d9c2716e'::uuid, 'I prefer tasks that involve configuring security tools and firewalls.', 'I am curious how tools can block unwanted connections to a computer network.'),
    ('e9d7862a-8953-4493-bb1d-cca04a17dbf3'::uuid, 'I am interested in the ethical considerations of security research.', 'I enjoy exploring how technology might be made safer by carefully looking for weaknesses.'),
    ('ff1b4e48-26b9-463d-b1d1-adaa64925ae1'::uuid, 'I enjoy working on problems that involve identifying and fixing security vulnerabilities.', 'I enjoy finding a weak point in a system and thinking through how to fix it.'),
    ('0566d310-5ab0-4ab6-99c0-ca614793e130'::uuid, 'I enjoy participating in product retrospectives and continuous improvement.', 'I enjoy looking back at how a project went and finding one way to improve next time.'),
    ('1ccf05c4-dd38-4939-ad23-77003077016d'::uuid, 'I prefer collaborating with designers and developers to build products.', 'I like helping people with different skills work together on a useful product.'),
    ('679594d9-8ee3-48df-a9d9-30b055ee1718'::uuid, 'I find it rewarding to prioritize features based on user value and business goals.', 'I enjoy choosing which product improvement will help people most and fit the project’s goal.'),
    ('7640a5a1-9a5d-4e6d-8ef5-f23ce77fe89c'::uuid, 'I enjoy understanding user needs and translating them into product features.', 'I enjoy understanding what people need and imagining a helpful tool or feature.'),
    ('a555ee82-ba5d-4417-a701-889a8c9fc79d'::uuid, 'I prefer working on problems that involve improving user experience.', 'I enjoy finding ways to make a digital tool easier and more helpful for the people who use it.'),
    ('765d8a35-a340-4ab1-b06f-6389d12283a4'::uuid, 'I am interested in learning about product management and product lifecycle.', 'I am curious how an idea is planned, built, introduced, and improved as a product.'),
    ('8aa63b33-2182-45fd-a490-0a2297301d72'::uuid, 'I am interested in learning about A/B testing and experimentation.', 'I am interested in comparing two versions of an idea to see which works better for people.'),
    ('947f0671-db35-4f10-9d97-bcdc2a15a84e'::uuid, 'I find satisfaction in advocating for the user''s perspective in product decisions.', 'I like speaking up for the people who will use a product when choices are made.'),
    ('967e238f-4ac7-46e6-81a6-4b0ea134723e'::uuid, 'I prefer tasks that involve creating user personas and journey maps.', 'I enjoy imagining the different people who may use an app and the steps they take to reach a goal.'),
    ('9d5e88b4-6204-476e-a69d-6f138bb03839'::uuid, 'I enjoy working with product analytics to measure success.', 'I enjoy using numbers about how a product is used to understand whether it is helping.'),
    ('9d75024d-91b0-4dbc-9b30-79863bdf874f'::uuid, 'I enjoy conducting user research and gathering feedback.', 'I enjoy asking people about their experience and using what I learn to improve a product.'),
    ('a979255f-6ce9-45f1-bb57-e6e97b830af8'::uuid, 'I prefer tasks that involve creating product roadmaps and release plans.', 'I like planning which improvements should be made first and when they could be ready.'),
    ('c306c9ba-e654-460b-902b-82be2f9dd1e6'::uuid, 'I am interested in learning about product pricing and monetization strategies.', 'I am curious how a product can create value for people and support the work needed to maintain it.'),
    ('f80bfb53-a771-40e3-b8b9-f911045d25f7'::uuid, 'I am interested in learning about agile and scrum methodologies.', 'I like organizing a project into clear steps, checking progress, and adjusting the plan as we learn.'),
    ('0db3d0da-c3cb-4cc2-aa31-3336e38e2594'::uuid, 'I find it rewarding to iterate on designs based on user feedback.', 'I enjoy improving a design after hearing how people respond to it.'),
    ('16551401-81d0-48d9-9e66-e842441eb1f2'::uuid, 'I am interested in learning about typography, color theory, and color theory, and layout.', 'I am interested in how type, color, and layout can make information clear and appealing.'),
    ('3e58bb10-459d-4fb4-a06c-0f002bf9a73d'::uuid, 'I prefer working on problems that involve improving usability and accessibility.', 'I enjoy making digital tools easy to use and welcoming to people with different needs.'),
    ('3fe286a0-ade4-402d-9356-d287baa47796'::uuid, 'I prefer tasks that involve designing for specific user groups (e.g., elderly, disabled).', 'I like considering how a design may work for people with different abilities and experiences.'),
    ('7cd6938f-c570-4500-aaff-18e58d4711c3'::uuid, 'I enjoy staying updated on the latest design trends and best practices.', 'I am curious about new visual styles and why some work well for people.'),
    ('95dcd9ca-1714-499f-9442-acc7fde36948'::uuid, 'I am interested in learning about design systems and component libraries.', 'I am interested in reusable visual pieces that help different screens feel consistent.'),
    ('aceef25a-cd26-4771-a1e9-5c92fc6aab3c'::uuid, 'I prefer learning about interaction design and micro-interactions.', 'I like designing small responses that show what happens when someone taps or changes something.'),
    ('b404aaa5-b752-4648-8573-476c0ce5c3e6'::uuid, 'I am interested in learning about user-centered design principles.', 'I am interested in starting a design by understanding what people need to do.'),
    ('b46e1741-f7eb-4a83-98b9-b77831d93bff'::uuid, 'I enjoy creating wireframes and prototypes to test design ideas.', 'I enjoy sketching a simple screen idea before deciding how it should look and work.'),
    ('cb9886a4-3497-464f-9a49-9c16f7aecc7b'::uuid, 'I prefer tasks that involve conducting usability testing with real users.', 'I would enjoy watching someone try a design and finding ways to make it easier for them.'),
    ('eef15c72-6682-45a8-a033-14cc14d3fe99'::uuid, 'I enjoy working with design tools like Figma, Sketch, or Adobe XD.', 'I would enjoy learning digital tools for creating and testing screen designs.'),
    ('fe39361b-d1ee-4819-8e38-7df41aa23d8c'::uuid, 'I find satisfaction in creating designs that work well across different devices.', 'I enjoy designing a screen that remains clear and easy to use on different devices.'),
    ('ff1d98f3-1a04-49a7-a1fc-724fb5446479'::uuid, 'I am interested in the psychological aspects of how users interact with technology.', 'I am curious how colors, wording, and feedback can affect how people feel when using technology.'),
    ('125e53a4-e4eb-4c6e-a052-45affc017446'::uuid, 'I enjoy mentoring and helping others develop their skills.', 'I enjoy helping someone build confidence and learn a new skill.'),
    ('18caead8-2165-4f7d-84de-9eab5a01f071'::uuid, 'I prefer working on problems that involve coordinating team members and tasks.', 'I like helping a group organize tasks so everyone knows what to do next.'),
    ('46a978a1-8313-420c-ac7a-fd9517d335e9'::uuid, 'I prefer tasks that involve identifying and mitigating project risks.', 'I enjoy noticing what might go wrong in a project and thinking ahead about solutions.'),
    ('4d695551-11cd-44f7-a856-9da448e7c251'::uuid, 'I find satisfaction in ensuring projects are completed on time and within budget.', 'I like helping a group make a realistic plan for time and resources and follow it through.'),
    ('5f6afc62-ffc0-49d9-814b-ab8b117de60e'::uuid, 'I am interested in learning about agile frameworks like Scrum and Kanban.', 'I am interested in organizing work on a shared project into small steps and adjusting as we learn.'),
    ('6cae208d-18a2-43a8-a513-4a09e850b685'::uuid, 'I find it rewarding to resolve conflicts and maintain team harmony.', 'I enjoy listening when people disagree and helping them find a way forward.'),
    ('6dc1f7f7-8ace-4f6e-a33f-89ec22101ea2'::uuid, 'I am interested in learning about project management methodologies.', 'I am interested in ways to plan work from the first idea through completion.'),
    ('6edca55a-373e-4061-bd59-d9eaa20e96c6'::uuid, 'I prefer tasks that involve setting clear goals and expectations for a team.', 'I like helping a group turn a broad idea into a clear goal everyone can understand.'),
    ('6fc01362-d01c-4cda-a982-8153c46fadbf'::uuid, 'I am interested in learning about risk management and contingency planning.', 'I would enjoy preparing a backup plan in case something unexpected happens.'),
    ('8e11f865-636b-4264-b2cc-5a6b74daf73b'::uuid, 'I enjoy taking on leadership roles in team projects.', 'I enjoy guiding a shared activity so people can make progress toward a common goal.'),
    ('c2185bab-ccaa-4f16-8365-997b56fcad95'::uuid, 'I prefer tasks that involve adapting plans based on changing requirements.', 'I can stay flexible and adjust a plan when new information changes what is needed.'),
    ('cdc34db6-7c16-4e4b-b157-77aec5452367'::uuid, 'I enjoy facilitating meetings and keeping discussions productive.', 'I like helping group conversations stay focused and making sure people can share ideas.'),
    ('d544e2c3-c773-4088-8fbe-bf5b32c272e0'::uuid, 'I am interested in learning about technical leadership and architecture decisions.', 'I am interested in helping a team make thoughtful choices about how technology is built.'),
    ('c2a17f49-fa80-420c-9491-35606a539ccf'::uuid, 'I find satisfaction in celebrating team successes and recognizing contributions.', 'I enjoy noticing and appreciating what each person contributes to a shared goal.'),
    ('fe9e6bd2-8f59-4c30-817a-06673ff3cabd'::uuid, 'I enjoy communicating project progress and updates to stakeholders.', 'I enjoy sharing clear progress updates with people who care about a project’s result.'),
    ('910f1acd-4847-4889-85a0-7ad9d2095a2f'::uuid, 'I enjoy working on projects that combine AI with other technologies.', 'I am curious how AI could work alongside other software tools to solve a practical problem.'),
    ('4c09fe7e-f25e-446a-ad35-ecdf47e9cff7'::uuid, 'I am interested in the ethical implications of AI in society.', 'I care about using AI in ways that are fair and helpful to people.'),
    ('8e2c469d-b08f-4d57-b11d-d2fdd20b7465'::uuid, 'I find satisfaction in seeing users benefit from the products I help create.', 'I would feel motivated by seeing a product help people with a real need.')
  ) AS changes(id, old_text, new_text)
  WHERE q.id = changes.id
    AND q.active = TRUE
    AND q.question_text IN (changes.old_text, changes.new_text);
  GET DIAGNOSTICS updated_rows = ROW_COUNT;
  IF updated_rows <> 109 THEN RAISE EXCEPTION 'Expected 109 rows, updated %; transaction rolled back', updated_rows; END IF;
END
$question_wording$;
COMMIT;
