-- CareerPath course-library checkpoint D. Guarded content-only updates for existing Full Stack records.
BEGIN;
DO $$
BEGIN
  IF (SELECT count(*) FROM public.courses WHERE id = 'full_stack' AND description = 'MERN stack development with advanced frontend and backend concepts.') <> 1 THEN RAISE EXCEPTION 'Full Stack course snapshot changed'; END IF;
  IF (SELECT count(*) FROM public.modules WHERE id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND course_id = 'full_stack' AND title = 'Frontend Development' AND module_order = 1 AND description = 'Building user interfaces and client-side applications') <> 1 THEN RAISE EXCEPTION 'Full Stack module snapshot changed: Frontend Development'; END IF;
  IF (SELECT count(*) FROM public.modules WHERE id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND course_id = 'full_stack' AND title = 'Backend Development and APIs' AND module_order = 2 AND description = 'Building server-side logic and application programming interfaces') <> 1 THEN RAISE EXCEPTION 'Full Stack module snapshot changed: Backend Development and APIs'; END IF;
  IF (SELECT count(*) FROM public.modules WHERE id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND course_id = 'full_stack' AND title = 'Database Design and DevOps' AND module_order = 3 AND description = 'Data storage, infrastructure, and deployment practices') <> 1 THEN RAISE EXCEPTION 'Full Stack module snapshot changed: Database Design and DevOps'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = '9884bbdb-9aae-4109-85c3-584259400d13' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'HTML5 and CSS3 Advanced' AND lesson_order = 1 AND content = 'Semantic elements, custom properties, gradients, transitions, and animations.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: HTML5 and CSS3 Advanced'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = 'c6924b8a-d0ac-4751-b68a-c64d80a19978' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'JavaScript ES6+ and TypeScript' AND lesson_order = 2 AND content = 'Arrow functions, destructuring, spread operator, modules, and static typing.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: JavaScript ES6+ and TypeScript'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = 'a15a1eba-8eb1-4cc2-9b6f-b64a46f95bc7' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'Frontend Frameworks: React and Vue' AND lesson_order = 3 AND content = 'Building reusable UI components with state management and routing capabilities.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: Frontend Frameworks: React and Vue'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = '64147c88-2331-4796-8ae2-4cc53ff04dbd' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'State Management and Data Flow' AND lesson_order = 4 AND content = 'Redux, Context API, Vuex, and other state management solutions.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: State Management and Data Flow'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = '93328a48-49e1-45ed-9dd7-9329ded3598e' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'Frontend Performance Optimization' AND lesson_order = 5 AND content = 'Code splitting, lazy loading, memoization, and optimizing rendering performance.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: Frontend Performance Optimization'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = '4ff3bf27-ab45-4067-a7fd-f59192440c5f' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'Node.js and Express.js' AND lesson_order = 1 AND content = 'Asynchronous event-driven JavaScript runtime designed to build scalable network applications.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: Node.js and Express.js'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = '661b3875-2dda-477b-9511-297f8c33a914' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'RESTful API Design' AND lesson_order = 2 AND content = 'Representational State Transfer architectural style for distributed hypermedia systems.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: RESTful API Design'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = 'b2507ee9-f71a-4db2-a0da-4728d4f3b867' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'Working with Databases' AND lesson_order = 3 AND content = 'Relational databases like MySQL and PostgreSQL, and MongoDB for document storage.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: Working with Databases'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = '1341fa71-f8e1-485e-bc06-2a1105a9158b' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'Authentication and Authorization' AND lesson_order = 4 AND content = 'Authentication verifies who you are, authorization determines what you can do.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: Authentication and Authorization'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = '0674dca3-e12e-4b8c-afa6-87c4e49d7021' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'API Documentation and Testing' AND lesson_order = 5 AND content = 'OpenAPI/Swagger documentation, Postman, and automated testing frameworks.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: API Documentation and Testing'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = 'd0b76a7d-64ff-4698-a33a-fc1502346422' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'Relational Database Design' AND lesson_order = 1 AND content = 'First normal form (1NF), second normal form (2NF), third normal form (3NF), and Boyce-Codd normal form (BCNF).') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: Relational Database Design'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = 'b5948158-7a09-4e19-a015-3315b7f84e26' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'NoSQL Data Modeling' AND lesson_order = 2 AND content = 'Modeling data for MongoDB, Cassandra, Redis, and similar databases.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: NoSQL Data Modeling'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = '3d112d5e-7783-48c9-8ed5-34c84dddd97e' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'Containerization with Docker' AND lesson_order = 3 AND content = 'Using Docker to create, deploy, and run applications in containers.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: Containerization with Docker'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = '1b1f1988-4f61-4283-b0ac-dfdb81d2524d' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'Infrastructure as Code (IaC)' AND lesson_order = 4 AND content = 'Terraform, AWS CloudFormation, and Ansible for provisioning and managing infrastructure.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: Infrastructure as Code (IaC)'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = '996c1fa3-4a8a-4f8f-91bb-64c494efc057' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'CI/CD Pipelines and Deployment Strategies' AND lesson_order = 5 AND content = 'Blue-green deployment, canary releases, and feature flags for safe deployments.') <> 1 THEN RAISE EXCEPTION 'Full Stack lesson snapshot changed: CI/CD Pipelines and Deployment Strategies'; END IF;
END $$;
UPDATE public.courses SET description = 'Trace a user action through browser UI, JavaScript, HTTP, APIs, server logic, validation, authorization, and database persistence; design and test basic endpoints, handle failures, and prepare a small web application for deployment.' WHERE id = 'full_stack' AND description = 'MERN stack development with advanced frontend and backend concepts.';
UPDATE public.modules SET description = 'Build accessible browser interfaces, manage client-side state, connect user actions to HTTP requests, and keep rendering responsive as data changes.' WHERE id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND course_id = 'full_stack' AND title = 'Frontend Development' AND module_order = 1 AND description = 'Building user interfaces and client-side applications';
UPDATE public.modules SET description = 'Implement request handlers and stable API contracts, validate untrusted input, enforce identity and permissions on the server, and return useful errors that the frontend can handle.' WHERE id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND course_id = 'full_stack' AND title = 'Backend Development and APIs' AND module_order = 2 AND description = 'Building server-side logic and application programming interfaces';
UPDATE public.modules SET description = 'Model durable records around application rules, choose relational or document storage from access patterns, and deploy a reproducible service with configuration, health checks, and rollback planning.' WHERE id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND course_id = 'full_stack' AND title = 'Database Design and DevOps' AND module_order = 3 AND description = 'Data storage, infrastructure, and deployment practices';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Build a semantic, responsive form and explain how browser structure and styling support a complete user task.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>A neighborhood library needs a page where residents can register for a workshop. The first mockup looks polished, but keyboard users cannot find the submit action and the event details are only communicated by color.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Which parts of the page describe meaning, which control appearance, and how can a user complete the task without a mouse?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>HTML gives content and controls structure; semantic elements help browsers, assistive technology, and developers understand their roles. CSS controls layout and presentation. A form submits named values, while labels, focus states, and clear errors make the interaction usable across devices.</p></section>
<section class="lesson-section"><h3>Example</h3><p>Use a form with a visible label for email, a required event choice, and a submit button. On a narrow screen, let fields fill the available width; show validation beside the relevant control rather than relying on color alone.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Sketch the workshop registration form with semantic elements. Identify each submitted field name, add a keyboard-visible focus state, and describe where an inline validation message should appear.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>The browser UI is the first link in a data path: accessible controls make user intent clear before JavaScript or a server handles it.</p></section>' WHERE id = '9884bbdb-9aae-4109-85c3-584259400d13' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'HTML5 and CSS3 Advanced' AND lesson_order = 1 AND content = 'Semantic elements, custom properties, gradients, transitions, and animations.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Trace a form event through JavaScript and distinguish local UI state from data that must be sent to a server.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>A resident submits the workshop form twice because the page gives no feedback while the network is slow. The interface needs to capture the values, prevent accidental duplicate clicks, and report success or failure.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>What should happen in the browser immediately, and what can only be confirmed after the server responds?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>JavaScript handles events and coordinates UI behavior. A typed request shape can make expected fields explicit, but types disappear at runtime and do not validate untrusted input. The browser should represent states such as idle, submitting, success, and error.</p></section>
<section class="lesson-section"><h3>Example</h3><p>A submit handler prevents the default navigation, reads FormData, disables the button while a request is pending, then displays a result based on the HTTP response. It should restore the button if the request fails.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Write pseudocode for submit handling that prevents a duplicate request, sends eventId and email, distinguishes a 4xx validation response from a network failure, and leaves entered values available after failure.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>Client-side logic improves interaction, but the server remains responsible for checking every value and deciding whether a change succeeded.</p></section>' WHERE id = 'c6924b8a-d0ac-4751-b68a-c64d80a19978' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'JavaScript ES6+ and TypeScript' AND lesson_order = 2 AND content = 'Arrow functions, destructuring, spread operator, modules, and static typing.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Connect a component event to a loading, success, or error view without treating framework state as persisted data.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>The workshop page has grown to include event details, registration fields, and confirmation. A developer changes the DOM directly in several places and the displayed registration count becomes inconsistent.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Which values should be the source of truth, and which parts of the page should be derived from them?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>Component frameworks organize UI around data and events. State represents the current client view; props or equivalent inputs pass data between components. Rendering state does not save it to a database, and a refresh can discard unsaved client state.</p></section>
<section class="lesson-section"><h3>Example</h3><p>Keep form values and request status in the registration form component. Pass the selected event as an input. Render a confirmation only after the API returns a successful response, not merely when the button is clicked.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Draw a small component tree for the workshop page. Mark the owner of selected event, form values, and request status, then identify which value must come from the server after a reload.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>Frameworks help keep a UI consistent; they do not replace the HTTP request or server-side source of truth.</p></section>' WHERE id = 'a15a1eba-8eb1-4cc2-9b6f-b64a46f95bc7' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'Frontend Frameworks: React and Vue' AND lesson_order = 3 AND content = 'Building reusable UI components with state management and routing capabilities.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Trace one registration value from input through client state and request payload, and identify when server data should refresh the view.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>A registration succeeds, but the page still shows the old attendee count. The form cleared itself before it knew whether the server accepted the request.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Which state is temporary input, which state is a server result, and what event should connect them?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>Client state may include draft form values, loading indicators, and cached server data. These have different lifetimes. A successful response can update or invalidate cached data; a failed response should preserve the draft and expose a recoverable error.</p></section>
<section class="lesson-section"><h3>Example</h3><p>After POST /api/events/42/registrations returns the saved registration and updated count, show confirmation and refresh the event summary. If it returns 409 because the event is full, keep the user’s input and show the reason.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Draw the state transitions for idle → submitting → success and idle → submitting → error. For each transition, state whether the form draft is retained and whether server data is refreshed.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>State becomes easier to reason about when each value has a clear owner and the UI changes in response to confirmed events.</p></section>' WHERE id = '64147c88-2331-4796-8ae2-4cc53ff04dbd' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'State Management and Data Flow' AND lesson_order = 4 AND content = 'Redux, Context API, Vuex, and other state management solutions.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Use browser evidence to locate a slow interaction and choose an optimization that preserves correct request behavior.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>The events page is slow on a phone. A developer adds memoization everywhere, but users still wait because each keystroke triggers a full list request and large event images dominate loading.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Which measurement would show whether the delay is rendering, network work, or asset loading?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>Performance work starts with measurement. Browser profiling and network inspection can distinguish expensive rendering, repeated requests, and large assets. Debouncing may reduce search calls; lazy loading and right-sized images reduce transfer, but optimizations must preserve accessibility and fresh data needs.</p></section>
<section class="lesson-section"><h3>Example</h3><p>Measure the search interaction, then debounce requests until typing pauses and cancel or ignore stale responses so an older query cannot overwrite newer results. Load below-the-fold images only when needed.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>For a slow event search, list one browser measurement for rendering, one network measurement, and one small change. Explain how you would verify the newest query still determines the displayed results.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>Optimize the measured bottleneck and retest behavior; a faster interface is still incorrect if stale responses replace current data.</p></section>' WHERE id = '93328a48-49e1-45ed-9dd7-9329ded3598e' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'Frontend Performance Optimization' AND lesson_order = 5 AND content = 'Code splitting, lazy loading, memoization, and optimizing rendering performance.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Trace an HTTP request through Express middleware to a route handler and explain how the server chooses a response.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>The registration button sends a request, but the page spins forever. The backend route parses the body, checks the event, saves a registration, and must return a response on every path.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>At which point can the request fail, and how does each failure reach the browser?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>Node.js runs JavaScript on the server; Express routes requests through middleware and handlers. A handler should parse only expected input, call application logic, await persistence, and send one deliberate response. Errors must reach centralized handling rather than leave requests hanging.</p></section>
<section class="lesson-section"><h3>Example</h3><p>A POST route validates eventId and email, asks the registration service to create the record, returns 201 with the saved result, maps a full event to 409, and passes unexpected failures to an error handler that logs a request ID.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Trace a POST request through body parsing, route validation, service, database, and response. Mark what the user sees if validation fails, the event is full, the database is unavailable, or no response is sent.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>A backend is the controlled bridge between HTTP requests and application rules; every path needs a safe, understandable outcome.</p></section>' WHERE id = '4ff3bf27-ab45-4067-a7fd-f59192440c5f' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'Node.js and Express.js' AND lesson_order = 1 AND content = 'Asynchronous event-driven JavaScript runtime designed to build scalable network applications.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Design a small resource-oriented API contract with appropriate methods, status codes, and stable request and response shapes.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>The browser and server team each implement registration differently: one sends a query parameter, the other expects JSON, and neither knows whether a timeout created a record.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>What contract would let both sides agree on the request, result, and retry behavior?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>An API contract defines resource paths, methods, input and output shapes, status codes, and error behavior. HTTP success does not guarantee the client received the response, so retry-sensitive actions need an idempotency strategy or a way to inspect the resulting resource.</p></section>
<section class="lesson-section"><h3>Example</h3><p>Use POST /api/events/42/registrations with JSON {email}. Return 201 and a registration ID when created, 400 for invalid input, 401 for missing identity, 403 for disallowed access, and 409 when capacity is full.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Write the request and response contract for creating and listing registrations. Include status codes for malformed input, unauthenticated requests, full capacity, and a retry after the first response was lost.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>A clear contract lets the UI and server evolve together while making errors and repeated requests predictable.</p></section>' WHERE id = '661b3875-2dda-477b-9511-297f8c33a914' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'RESTful API Design' AND lesson_order = 2 AND content = 'Representational State Transfer architectural style for distributed hypermedia systems.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Follow a write request through a database operation and distinguish a confirmed commit from an attempted save.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>The API returns “registered” before the database write finishes. When the database rejects a duplicate email, the browser has already displayed success.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>What must the server wait for before it can report success?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>A database stores durable application records; the server maps domain operations to queries or transactions. It should await the operation and translate known constraint failures into safe application errors. A successful response should reflect committed data, not an optimistic assumption.</p></section>
<section class="lesson-section"><h3>Example</h3><p>Create a unique constraint on event_id and normalized email. Attempt the insert, return the saved row after commit, and map a uniqueness conflict to an “already registered” response without exposing SQL details.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Trace a registration from JSON body to normalized values, database insert, and HTTP response. Identify what happens if the connection fails before commit and after commit but before the response reaches the browser.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>Persistence is part of request correctness: report success only when the intended state change is confirmed.</p></section>' WHERE id = 'b2507ee9-f71a-4db2-a0da-4728d4f3b867' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'Working with Databases' AND lesson_order = 3 AND content = 'Relational databases like MySQL and PostgreSQL, and MongoDB for document storage.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Separate identity verification from permission checks and enforce both at the server boundary for a protected action.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>A user changes an event ID in the browser request and successfully edits another organizer’s workshop. Hiding the edit button did not protect the data.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Which server-side facts must be checked before applying the update?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>Authentication establishes who the request represents; authorization decides whether that identity may perform this action on this resource. Client UI checks are for experience, not security. The server must verify the session or token and evaluate ownership or role for every protected request.</p></section>
<section class="lesson-section"><h3>Example</h3><p>For PATCH /api/events/42, authenticate the session, load event 42, compare its organizer_id with the verified user or an authorized admin role, validate permitted fields, then update. Return 401 when identity is absent and 403 when permission is insufficient.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Review a route that accepts eventId and title. List the identity, ownership, and field checks it needs; explain why checking only whether a user is logged in is insufficient.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>The browser may guide a user, but only server-side authorization can protect a resource from a crafted request.</p></section>' WHERE id = '1341fa71-f8e1-485e-bc06-2a1105a9158b' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'Authentication and Authorization' AND lesson_order = 4 AND content = 'Authentication verifies who you are, authorization determines what you can do.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Turn an API contract into executable checks for normal, invalid, unauthorized, and failed requests.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>A release breaks workshop registration because the frontend assumes a 200 response while the API correctly returns 201. The only test checked that the route did not crash.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Which contract details should a test protect beyond basic availability?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>API tests verify observable behavior: status, response shape, validation, identity and permission boundaries, persistence, and error handling. Documentation should describe the same contract that tests exercise, including examples and failure responses.</p></section>
<section class="lesson-section"><h3>Example</h3><p>Test a valid create request and assert 201 plus a registration ID; submit an invalid email and assert 400; repeat the request and assert the documented duplicate behavior; verify an anonymous request cannot create a protected registration.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Write four API checks for registration covering valid input, malformed input, no session, and a database failure. For each, state the expected status and whether a database row should exist.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>Tests and documentation make the frontend-server agreement inspectable and catch regressions before users encounter them.</p></section>' WHERE id = '0674dca3-e12e-4b8c-afa6-87c4e49d7021' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'API Documentation and Testing' AND lesson_order = 5 AND content = 'OpenAPI/Swagger documentation, Postman, and automated testing frameworks.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Model users, events, and registrations with keys and constraints that keep relationships valid under concurrent requests.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>Two residents claim the last seat at the same time. Both requests read one remaining place and insert a registration, so the event now exceeds capacity.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Which rules belong only in application code, and which invariants should the database help enforce?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>Relational tables represent entities and relationships through keys. Constraints protect invariants such as unique registration per event and valid foreign keys. Multi-step changes may require a transaction or atomic conditional update to avoid race conditions.</p></section>
<section class="lesson-section"><h3>Example</h3><p>Store events and registrations separately, reference events with a foreign key, and add a unique constraint on event_id plus normalized email. Reserve capacity with an atomic update or transaction that checks remaining seats while writing the registration.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Sketch event and registration tables with primary and foreign keys. State how you would prevent duplicate registrations and two concurrent requests from taking the final seat.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>A sound schema makes important data rules explicit and helps preserve them when requests arrive concurrently.</p></section>' WHERE id = 'd0b76a7d-64ff-4698-a33a-fc1502346422' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'Relational Database Design' AND lesson_order = 1 AND content = 'First normal form (1NF), second normal form (2NF), third normal form (3NF), and Boyce-Codd normal form (BCNF).';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Choose a document-oriented model from read and write patterns and identify the consistency cost of duplicated data.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>The event page must load quickly, so a team copies organizer details into every event document. An organizer changes their display name and old event documents become inconsistent.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Which reads benefit from embedding, and what update work does duplication create?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>Document databases group related data around access patterns. Embedding can make common reads simpler; references reduce repeated data but may require more reads. Denormalized copies need an update strategy and do not replace validation or authorization.</p></section>
<section class="lesson-section"><h3>Example</h3><p>Embed a small immutable venue snapshot needed for each event card, but reference the organizer profile as canonical data. If a name snapshot is needed for historical display, label and preserve it intentionally.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>For events, choose which fields to embed and which to reference. Describe one likely query, one update, and how you would prevent a stale duplicated organizer field from misleading users.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>Choose a data model from real access patterns and document the consistency trade-offs it introduces.</p></section>' WHERE id = 'b5948158-7a09-4e19-a015-3315b7f84e26' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'NoSQL Data Modeling' AND lesson_order = 2 AND content = 'Modeling data for MongoDB, Cassandra, Redis, and similar databases.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Explain how a container image packages an application and distinguish build-time inputs from runtime configuration.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>The registration service works on a developer’s laptop but fails after deployment because it relied on a local file and a secret stored in a shell profile.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>What belongs in the image, and what must be provided safely when the container runs?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>A container image packages application code and its runtime dependencies. Environment-specific settings and secrets should be injected at runtime through the hosting environment or secret manager. Persistent user data belongs in managed storage, not an ephemeral container filesystem.</p></section>
<section class="lesson-section"><h3>Example</h3><p>Build the server image from a lockfile and production build steps. At runtime provide the database URL through protected configuration, expose a health endpoint, and write logs to standard output without printing credentials.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Review a Docker setup that copies a local .env file into the image and writes uploads to a container directory. Identify two deployment risks and propose a safer configuration or storage boundary.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>Reproducible packaging reduces environment drift, while runtime configuration and durable data stay outside the image.</p></section>' WHERE id = '3d112d5e-7783-48c9-8ed5-34c84dddd97e' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'Containerization with Docker' AND lesson_order = 3 AND content = 'Using Docker to create, deploy, and run applications in containers.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Describe deployment infrastructure as reviewable configuration and identify which settings require protected values or environment separation.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>A teammate manually changes the production database firewall during an incident, but the change is absent from the repository and disappears during the next rebuild.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>How can the team make infrastructure changes repeatable without committing credentials?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>Infrastructure as code records desired resources and relationships in version-controlled configuration. Plans or previews expose intended changes before apply. Environments should be separated, permissions limited, and secrets supplied by a protected secret store rather than source files.</p></section>
<section class="lesson-section"><h3>Example</h3><p>Define a web service, private database access, and health check as reviewed configuration. Keep production credentials in the platform’s secret settings and use a separate state backend with controlled access.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Given a proposed infrastructure change that opens a database port to the public internet, identify the review evidence you need, a safer network rule, and where the credential should live.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>Infrastructure changes become safer when they are reviewable, repeatable, scoped, and separated from secret values.</p></section>' WHERE id = '1b1f1988-4f61-4283-b0ac-dfdb81d2524d' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'Infrastructure as Code (IaC)' AND lesson_order = 4 AND content = 'Terraform, AWS CloudFormation, and Ansible for provisioning and managing infrastructure.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>Plan an end-to-end release for a small full-stack application, including automated checks, configuration, health verification, rollback, and a clear project presentation.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>The workshop application works locally, but after a release registrations fail because the production API points at a missing database setting. A polished demo had never exercised the deployed request path.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>What evidence would show that a real user can complete the whole task after deployment, and how could the team recover if the release fails?</p></section>
<section class="lesson-section"><h3>Concept</h3><p>A delivery pipeline builds a known revision, runs checks, and deploys through controlled stages. Production readiness also depends on runtime configuration, database compatibility, health signals, observability, and a rollback or forward-fix plan. Blue-green or canary rollout can reduce exposure when the platform supports them, but do not replace verification.</p></section>
<section class="lesson-section"><h3>Example</h3><p>For the workshop registration app, run tests and build from the committed revision, apply a reviewed compatible schema change, deploy to a staging URL, submit a test registration through the browser, check logs and health, then promote gradually and monitor error rate. Keep the previous deploy available for rollback.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Capstone: design and demonstrate a small workshop registration application. Include the user problem and intended users; requirements and acceptance checks; frontend form and states; API methods and response shapes; event/registration data model; validation; authentication and organizer authorization; duplicate/full-event and database errors; tests for normal and failure paths; configuration, health checks, monitoring, deployment, and rollback. Present it in this order: (1) What did you build? (2) What problem does it solve? (3) Who is it for? (4) How does the system work? (5) What does the frontend do? (6) What does the backend do? (7) How is data stored? (8) How did you handle authentication/security? (9) What problems did you encounter? (10) What would you improve? (11) What would you change before production? Show one successful request and one failure path; distinguish tested behavior from planned work.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>A deployment is the final part of the request path: verify the user journey in its real environment and preserve a safe recovery option.</p></section>' WHERE id = '996c1fa3-4a8a-4f8f-91bb-64c494efc057' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'CI/CD Pipelines and Deployment Strategies' AND lesson_order = 5 AND content = 'Blue-green deployment, canary releases, and feature flags for safe deployments.';
COMMIT;

-- Rollback template:--  restores exact original descriptions and lesson bodies if run after this migration.
-- BEGIN;
-- UPDATE public.courses SET description = 'MERN stack development with advanced frontend and backend concepts.' WHERE id = 'full_stack' AND description = 'Trace a user action through browser UI, JavaScript, HTTP, APIs, server logic, validation, authorization, and database persistence; design and test basic endpoints, handle failures, and prepare a small web application for deployment.';
-- UPDATE public.modules SET description = 'Building user interfaces and client-side applications' WHERE id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND course_id = 'full_stack' AND title = 'Frontend Development' AND module_order = 1 AND description = 'Build accessible browser interfaces, manage client-side state, connect user actions to HTTP requests, and keep rendering responsive as data changes.';
-- UPDATE public.modules SET description = 'Building server-side logic and application programming interfaces' WHERE id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND course_id = 'full_stack' AND title = 'Backend Development and APIs' AND module_order = 2 AND description = 'Implement request handlers and stable API contracts, validate untrusted input, enforce identity and permissions on the server, and return useful errors that the frontend can handle.';
-- UPDATE public.modules SET description = 'Data storage, infrastructure, and deployment practices' WHERE id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND course_id = 'full_stack' AND title = 'Database Design and DevOps' AND module_order = 3 AND description = 'Model durable records around application rules, choose relational or document storage from access patterns, and deploy a reproducible service with configuration, health checks, and rollback planning.';
-- UPDATE public.lessons SET content = 'Semantic elements, custom properties, gradients, transitions, and animations.' WHERE id = '9884bbdb-9aae-4109-85c3-584259400d13' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'HTML5 and CSS3 Advanced' AND lesson_order = 1 AND content = '<section class="lesson-section"><h3>Story</h3><p>Build a semantic, responsive form and explain how browser structure and styling support a complete user task.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>A neighborhood library needs a page where residents can register for a workshop. The first mockup looks polished, but keyboard users cannot find the submit action and the event details are only communicated by color.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>Which parts of the page describe meaning, which control appearance, and how can a user complete the task without a mouse?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>HTML gives content and controls structure; semantic elements help browsers, assistive technology, and developers understand their roles. CSS controls layout and presentation. A form submits named values, while labels, focus states, and clear errors make the interaction usable across devices.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>Use a form with a visible label for email, a required event choice, and a submit button. On a narrow screen, let fields fill the available width; show validation beside the relevant control rather than relying on color alone.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Sketch the workshop registration form with semantic elements. Identify each submitted field name, add a keyboard-visible focus state, and describe where an inline validation message should appear.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>The browser UI is the first link in a data path: accessible controls make user intent clear before JavaScript or a server handles it.</p></section>';
-- UPDATE public.lessons SET content = 'Arrow functions, destructuring, spread operator, modules, and static typing.' WHERE id = 'c6924b8a-d0ac-4751-b68a-c64d80a19978' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'JavaScript ES6+ and TypeScript' AND lesson_order = 2 AND content = '<section class="lesson-section"><h3>Story</h3><p>Trace a form event through JavaScript and distinguish local UI state from data that must be sent to a server.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>A resident submits the workshop form twice because the page gives no feedback while the network is slow. The interface needs to capture the values, prevent accidental duplicate clicks, and report success or failure.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>What should happen in the browser immediately, and what can only be confirmed after the server responds?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>JavaScript handles events and coordinates UI behavior. A typed request shape can make expected fields explicit, but types disappear at runtime and do not validate untrusted input. The browser should represent states such as idle, submitting, success, and error.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>A submit handler prevents the default navigation, reads FormData, disables the button while a request is pending, then displays a result based on the HTTP response. It should restore the button if the request fails.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Write pseudocode for submit handling that prevents a duplicate request, sends eventId and email, distinguishes a 4xx validation response from a network failure, and leaves entered values available after failure.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>Client-side logic improves interaction, but the server remains responsible for checking every value and deciding whether a change succeeded.</p></section>';
-- UPDATE public.lessons SET content = 'Building reusable UI components with state management and routing capabilities.' WHERE id = 'a15a1eba-8eb1-4cc2-9b6f-b64a46f95bc7' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'Frontend Frameworks: React and Vue' AND lesson_order = 3 AND content = '<section class="lesson-section"><h3>Story</h3><p>Connect a component event to a loading, success, or error view without treating framework state as persisted data.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>The workshop page has grown to include event details, registration fields, and confirmation. A developer changes the DOM directly in several places and the displayed registration count becomes inconsistent.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>Which values should be the source of truth, and which parts of the page should be derived from them?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>Component frameworks organize UI around data and events. State represents the current client view; props or equivalent inputs pass data between components. Rendering state does not save it to a database, and a refresh can discard unsaved client state.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>Keep form values and request status in the registration form component. Pass the selected event as an input. Render a confirmation only after the API returns a successful response, not merely when the button is clicked.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Draw a small component tree for the workshop page. Mark the owner of selected event, form values, and request status, then identify which value must come from the server after a reload.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>Frameworks help keep a UI consistent; they do not replace the HTTP request or server-side source of truth.</p></section>';
-- UPDATE public.lessons SET content = 'Redux, Context API, Vuex, and other state management solutions.' WHERE id = '64147c88-2331-4796-8ae2-4cc53ff04dbd' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'State Management and Data Flow' AND lesson_order = 4 AND content = '<section class="lesson-section"><h3>Story</h3><p>Trace one registration value from input through client state and request payload, and identify when server data should refresh the view.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>A registration succeeds, but the page still shows the old attendee count. The form cleared itself before it knew whether the server accepted the request.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>Which state is temporary input, which state is a server result, and what event should connect them?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>Client state may include draft form values, loading indicators, and cached server data. These have different lifetimes. A successful response can update or invalidate cached data; a failed response should preserve the draft and expose a recoverable error.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>After POST /api/events/42/registrations returns the saved registration and updated count, show confirmation and refresh the event summary. If it returns 409 because the event is full, keep the user’s input and show the reason.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Draw the state transitions for idle → submitting → success and idle → submitting → error. For each transition, state whether the form draft is retained and whether server data is refreshed.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>State becomes easier to reason about when each value has a clear owner and the UI changes in response to confirmed events.</p></section>';
-- UPDATE public.lessons SET content = 'Code splitting, lazy loading, memoization, and optimizing rendering performance.' WHERE id = '93328a48-49e1-45ed-9dd7-9329ded3598e' AND module_id = 'ace43463-c0d8-4cb8-990e-19d42c4cf624' AND title = 'Frontend Performance Optimization' AND lesson_order = 5 AND content = '<section class="lesson-section"><h3>Story</h3><p>Use browser evidence to locate a slow interaction and choose an optimization that preserves correct request behavior.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>The events page is slow on a phone. A developer adds memoization everywhere, but users still wait because each keystroke triggers a full list request and large event images dominate loading.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>Which measurement would show whether the delay is rendering, network work, or asset loading?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>Performance work starts with measurement. Browser profiling and network inspection can distinguish expensive rendering, repeated requests, and large assets. Debouncing may reduce search calls; lazy loading and right-sized images reduce transfer, but optimizations must preserve accessibility and fresh data needs.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>Measure the search interaction, then debounce requests until typing pauses and cancel or ignore stale responses so an older query cannot overwrite newer results. Load below-the-fold images only when needed.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>For a slow event search, list one browser measurement for rendering, one network measurement, and one small change. Explain how you would verify the newest query still determines the displayed results.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>Optimize the measured bottleneck and retest behavior; a faster interface is still incorrect if stale responses replace current data.</p></section>';
-- UPDATE public.lessons SET content = 'Asynchronous event-driven JavaScript runtime designed to build scalable network applications.' WHERE id = '4ff3bf27-ab45-4067-a7fd-f59192440c5f' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'Node.js and Express.js' AND lesson_order = 1 AND content = '<section class="lesson-section"><h3>Story</h3><p>Trace an HTTP request through Express middleware to a route handler and explain how the server chooses a response.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>The registration button sends a request, but the page spins forever. The backend route parses the body, checks the event, saves a registration, and must return a response on every path.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>At which point can the request fail, and how does each failure reach the browser?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>Node.js runs JavaScript on the server; Express routes requests through middleware and handlers. A handler should parse only expected input, call application logic, await persistence, and send one deliberate response. Errors must reach centralized handling rather than leave requests hanging.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>A POST route validates eventId and email, asks the registration service to create the record, returns 201 with the saved result, maps a full event to 409, and passes unexpected failures to an error handler that logs a request ID.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Trace a POST request through body parsing, route validation, service, database, and response. Mark what the user sees if validation fails, the event is full, the database is unavailable, or no response is sent.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>A backend is the controlled bridge between HTTP requests and application rules; every path needs a safe, understandable outcome.</p></section>';
-- UPDATE public.lessons SET content = 'Representational State Transfer architectural style for distributed hypermedia systems.' WHERE id = '661b3875-2dda-477b-9511-297f8c33a914' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'RESTful API Design' AND lesson_order = 2 AND content = '<section class="lesson-section"><h3>Story</h3><p>Design a small resource-oriented API contract with appropriate methods, status codes, and stable request and response shapes.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>The browser and server team each implement registration differently: one sends a query parameter, the other expects JSON, and neither knows whether a timeout created a record.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>What contract would let both sides agree on the request, result, and retry behavior?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>An API contract defines resource paths, methods, input and output shapes, status codes, and error behavior. HTTP success does not guarantee the client received the response, so retry-sensitive actions need an idempotency strategy or a way to inspect the resulting resource.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>Use POST /api/events/42/registrations with JSON {email}. Return 201 and a registration ID when created, 400 for invalid input, 401 for missing identity, 403 for disallowed access, and 409 when capacity is full.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Write the request and response contract for creating and listing registrations. Include status codes for malformed input, unauthenticated requests, full capacity, and a retry after the first response was lost.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>A clear contract lets the UI and server evolve together while making errors and repeated requests predictable.</p></section>';
-- UPDATE public.lessons SET content = 'Relational databases like MySQL and PostgreSQL, and MongoDB for document storage.' WHERE id = 'b2507ee9-f71a-4db2-a0da-4728d4f3b867' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'Working with Databases' AND lesson_order = 3 AND content = '<section class="lesson-section"><h3>Story</h3><p>Follow a write request through a database operation and distinguish a confirmed commit from an attempted save.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>The API returns “registered” before the database write finishes. When the database rejects a duplicate email, the browser has already displayed success.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>What must the server wait for before it can report success?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>A database stores durable application records; the server maps domain operations to queries or transactions. It should await the operation and translate known constraint failures into safe application errors. A successful response should reflect committed data, not an optimistic assumption.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>Create a unique constraint on event_id and normalized email. Attempt the insert, return the saved row after commit, and map a uniqueness conflict to an “already registered” response without exposing SQL details.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Trace a registration from JSON body to normalized values, database insert, and HTTP response. Identify what happens if the connection fails before commit and after commit but before the response reaches the browser.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>Persistence is part of request correctness: report success only when the intended state change is confirmed.</p></section>';
-- UPDATE public.lessons SET content = 'Authentication verifies who you are, authorization determines what you can do.' WHERE id = '1341fa71-f8e1-485e-bc06-2a1105a9158b' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'Authentication and Authorization' AND lesson_order = 4 AND content = '<section class="lesson-section"><h3>Story</h3><p>Separate identity verification from permission checks and enforce both at the server boundary for a protected action.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>A user changes an event ID in the browser request and successfully edits another organizer’s workshop. Hiding the edit button did not protect the data.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>Which server-side facts must be checked before applying the update?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>Authentication establishes who the request represents; authorization decides whether that identity may perform this action on this resource. Client UI checks are for experience, not security. The server must verify the session or token and evaluate ownership or role for every protected request.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>For PATCH /api/events/42, authenticate the session, load event 42, compare its organizer_id with the verified user or an authorized admin role, validate permitted fields, then update. Return 401 when identity is absent and 403 when permission is insufficient.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Review a route that accepts eventId and title. List the identity, ownership, and field checks it needs; explain why checking only whether a user is logged in is insufficient.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>The browser may guide a user, but only server-side authorization can protect a resource from a crafted request.</p></section>';
-- UPDATE public.lessons SET content = 'OpenAPI/Swagger documentation, Postman, and automated testing frameworks.' WHERE id = '0674dca3-e12e-4b8c-afa6-87c4e49d7021' AND module_id = '6ecc9754-977d-48f6-bca6-64e104b3251b' AND title = 'API Documentation and Testing' AND lesson_order = 5 AND content = '<section class="lesson-section"><h3>Story</h3><p>Turn an API contract into executable checks for normal, invalid, unauthorized, and failed requests.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>A release breaks workshop registration because the frontend assumes a 200 response while the API correctly returns 201. The only test checked that the route did not crash.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>Which contract details should a test protect beyond basic availability?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>API tests verify observable behavior: status, response shape, validation, identity and permission boundaries, persistence, and error handling. Documentation should describe the same contract that tests exercise, including examples and failure responses.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>Test a valid create request and assert 201 plus a registration ID; submit an invalid email and assert 400; repeat the request and assert the documented duplicate behavior; verify an anonymous request cannot create a protected registration.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Write four API checks for registration covering valid input, malformed input, no session, and a database failure. For each, state the expected status and whether a database row should exist.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>Tests and documentation make the frontend-server agreement inspectable and catch regressions before users encounter them.</p></section>';
-- UPDATE public.lessons SET content = 'First normal form (1NF), second normal form (2NF), third normal form (3NF), and Boyce-Codd normal form (BCNF).' WHERE id = 'd0b76a7d-64ff-4698-a33a-fc1502346422' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'Relational Database Design' AND lesson_order = 1 AND content = '<section class="lesson-section"><h3>Story</h3><p>Model users, events, and registrations with keys and constraints that keep relationships valid under concurrent requests.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>Two residents claim the last seat at the same time. Both requests read one remaining place and insert a registration, so the event now exceeds capacity.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>Which rules belong only in application code, and which invariants should the database help enforce?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>Relational tables represent entities and relationships through keys. Constraints protect invariants such as unique registration per event and valid foreign keys. Multi-step changes may require a transaction or atomic conditional update to avoid race conditions.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>Store events and registrations separately, reference events with a foreign key, and add a unique constraint on event_id plus normalized email. Reserve capacity with an atomic update or transaction that checks remaining seats while writing the registration.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Sketch event and registration tables with primary and foreign keys. State how you would prevent duplicate registrations and two concurrent requests from taking the final seat.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>A sound schema makes important data rules explicit and helps preserve them when requests arrive concurrently.</p></section>';
-- UPDATE public.lessons SET content = 'Modeling data for MongoDB, Cassandra, Redis, and similar databases.' WHERE id = 'b5948158-7a09-4e19-a015-3315b7f84e26' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'NoSQL Data Modeling' AND lesson_order = 2 AND content = '<section class="lesson-section"><h3>Story</h3><p>Choose a document-oriented model from read and write patterns and identify the consistency cost of duplicated data.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>The event page must load quickly, so a team copies organizer details into every event document. An organizer changes their display name and old event documents become inconsistent.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>Which reads benefit from embedding, and what update work does duplication create?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>Document databases group related data around access patterns. Embedding can make common reads simpler; references reduce repeated data but may require more reads. Denormalized copies need an update strategy and do not replace validation or authorization.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>Embed a small immutable venue snapshot needed for each event card, but reference the organizer profile as canonical data. If a name snapshot is needed for historical display, label and preserve it intentionally.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>For events, choose which fields to embed and which to reference. Describe one likely query, one update, and how you would prevent a stale duplicated organizer field from misleading users.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>Choose a data model from real access patterns and document the consistency trade-offs it introduces.</p></section>';
-- UPDATE public.lessons SET content = 'Using Docker to create, deploy, and run applications in containers.' WHERE id = '3d112d5e-7783-48c9-8ed5-34c84dddd97e' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'Containerization with Docker' AND lesson_order = 3 AND content = '<section class="lesson-section"><h3>Story</h3><p>Explain how a container image packages an application and distinguish build-time inputs from runtime configuration.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>The registration service works on a developer’s laptop but fails after deployment because it relied on a local file and a secret stored in a shell profile.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>What belongs in the image, and what must be provided safely when the container runs?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>A container image packages application code and its runtime dependencies. Environment-specific settings and secrets should be injected at runtime through the hosting environment or secret manager. Persistent user data belongs in managed storage, not an ephemeral container filesystem.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>Build the server image from a lockfile and production build steps. At runtime provide the database URL through protected configuration, expose a health endpoint, and write logs to standard output without printing credentials.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Review a Docker setup that copies a local .env file into the image and writes uploads to a container directory. Identify two deployment risks and propose a safer configuration or storage boundary.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>Reproducible packaging reduces environment drift, while runtime configuration and durable data stay outside the image.</p></section>';
-- UPDATE public.lessons SET content = 'Terraform, AWS CloudFormation, and Ansible for provisioning and managing infrastructure.' WHERE id = '1b1f1988-4f61-4283-b0ac-dfdb81d2524d' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'Infrastructure as Code (IaC)' AND lesson_order = 4 AND content = '<section class="lesson-section"><h3>Story</h3><p>Describe deployment infrastructure as reviewable configuration and identify which settings require protected values or environment separation.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>A teammate manually changes the production database firewall during an incident, but the change is absent from the repository and disappears during the next rebuild.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>How can the team make infrastructure changes repeatable without committing credentials?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>Infrastructure as code records desired resources and relationships in version-controlled configuration. Plans or previews expose intended changes before apply. Environments should be separated, permissions limited, and secrets supplied by a protected secret store rather than source files.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>Define a web service, private database access, and health check as reviewed configuration. Keep production credentials in the platform’s secret settings and use a separate state backend with controlled access.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Given a proposed infrastructure change that opens a database port to the public internet, identify the review evidence you need, a safer network rule, and where the credential should live.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>Infrastructure changes become safer when they are reviewable, repeatable, scoped, and separated from secret values.</p></section>';
-- UPDATE public.lessons SET content = 'Blue-green deployment, canary releases, and feature flags for safe deployments.' WHERE id = '996c1fa3-4a8a-4f8f-91bb-64c494efc057' AND module_id = '45411f32-2355-464a-90c5-c1fd586b47aa' AND title = 'CI/CD Pipelines and Deployment Strategies' AND lesson_order = 5 AND content = '<section class="lesson-section"><h3>Story</h3><p>Plan an end-to-end release for a small full-stack application, including automated checks, configuration, health verification, rollback, and a clear project presentation.</p></section>
-- <section class="lesson-section"><h3>Discovery</h3><p>The workshop application works locally, but after a release registrations fail because the production API points at a missing database setting. A polished demo had never exercised the deployed request path.</p></section>
-- <section class="lesson-section"><h3>Learning Objective</h3><p>What evidence would show that a real user can complete the whole task after deployment, and how could the team recover if the release fails?</p></section>
-- <section class="lesson-section"><h3>Concept</h3><p>A delivery pipeline builds a known revision, runs checks, and deploys through controlled stages. Production readiness also depends on runtime configuration, database compatibility, health signals, observability, and a rollback or forward-fix plan. Blue-green or canary rollout can reduce exposure when the platform supports them, but do not replace verification.</p></section>
-- <section class="lesson-section"><h3>Example</h3><p>For the workshop registration app, run tests and build from the committed revision, apply a reviewed compatible schema change, deploy to a staging URL, submit a test registration through the browser, check logs and health, then promote gradually and monitor error rate. Keep the previous deploy available for rollback.</p></section>
-- <section class="lesson-section"><h3>Challenge</h3><p>Capstone: design and demonstrate a small workshop registration application. Include the user problem and intended users; requirements and acceptance checks; frontend form and states; API methods and response shapes; event/registration data model; validation; authentication and organizer authorization; duplicate/full-event and database errors; tests for normal and failure paths; configuration, health checks, monitoring, deployment, and rollback. Present it in this order: (1) What did you build? (2) What problem does it solve? (3) Who is it for? (4) How does the system work? (5) What does the frontend do? (6) What does the backend do? (7) How is data stored? (8) How did you handle authentication/security? (9) What problems did you encounter? (10) What would you improve? (11) What would you change before production? Show one successful request and one failure path; distinguish tested behavior from planned work.</p></section>
-- <section class="lesson-section"><h3>Takeaway</h3><p>A deployment is the final part of the request path: verify the user journey in its real environment and preserve a safe recovery option.</p></section>';
-- COMMIT;

-- Targeted modern-course terminology clarifications for checkpoint D.
BEGIN;
DO $$
BEGIN
  IF (SELECT count(*) FROM public.courses WHERE id = 'prompt_engineering' AND description = 'Design, test, and improve prompts and multi-step LLM workflows for useful, verifiable outcomes.') <> 1 THEN RAISE EXCEPTION 'Modern course snapshot changed: prompt_engineering'; END IF;
  IF (SELECT count(*) FROM public.courses WHERE id = 'generative_ai_llm' AND description = 'Build LLM applications using model APIs, structured outputs, embeddings, conversation state, and practical reliability controls.') <> 1 THEN RAISE EXCEPTION 'Modern course snapshot changed: generative_ai_llm'; END IF;
  IF (SELECT count(*) FROM public.courses WHERE id = 'mcp_tool_connected_ai' AND description = 'Connect AI applications to external capabilities using MCP concepts, server-provided tools/resources, and explicit permissions.') <> 1 THEN RAISE EXCEPTION 'Modern course snapshot changed: mcp_tool_connected_ai'; END IF;
  IF (SELECT count(*) FROM public.lessons WHERE id = '80f74c3a-492f-4efe-aaba-4ae628c9721a' AND module_id = 'eb427a53-1c31-4c0b-91fd-bfdfdfb806af' AND title = 'MCP and Adjacent Integration Patterns' AND lesson_order = 2 AND content = '<section class="lesson-section"><h3>Story</h3><p>A desktop assistant can explain a spreadsheet formula but cannot inspect the user&#39;s authorized workbook until connected to a capability.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>Identify what the model can infer and what requires an external, permissioned tool or resource.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Distinguish MCP from direct API calls and model function-calling schemas.</p></section>
<section class="lesson-section"><h3>Concept</h3><p>MCP is a protocol for connecting AI applications with servers that expose capabilities such as tools, resources, and prompts. A direct API is an application-specific interface; function calling is a model interaction pattern and may be used inside an MCP-enabled host.</p></section>
<section class="lesson-section"><h3>Example</h3><p>A host can discover an MCP server&#39;s tools, while a separate model call decides whether to propose one of those tools.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Classify four integration diagrams as direct API, function calling, MCP, or combinations and explain the protocol boundary.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>MCP standardizes a connection protocol; it is not itself a model or a generic synonym for APIs.</p></section>') <> 1 THEN RAISE EXCEPTION 'MCP lesson snapshot changed'; END IF;
END $$;
UPDATE public.courses SET description = 'Design, test, and improve prompts and multi-step large language model (LLM) workflows for useful, verifiable outcomes.' WHERE id = 'prompt_engineering' AND description = 'Design, test, and improve prompts and multi-step LLM workflows for useful, verifiable outcomes.';
UPDATE public.courses SET description = 'Build large language model (LLM) applications using model APIs, structured outputs, embeddings, conversation state, and practical reliability controls.' WHERE id = 'generative_ai_llm' AND description = 'Build LLM applications using model APIs, structured outputs, embeddings, conversation state, and practical reliability controls.';
UPDATE public.courses SET description = 'Connect AI applications to external capabilities using the Model Context Protocol (MCP), server-provided tools/resources, and explicit permissions.' WHERE id = 'mcp_tool_connected_ai' AND description = 'Connect AI applications to external capabilities using MCP concepts, server-provided tools/resources, and explicit permissions.';
UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>A desktop assistant can explain a spreadsheet formula but cannot inspect the user&#39;s authorized workbook until connected to a capability.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>Identify what the model can infer and what requires an external, permissioned tool or resource.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Distinguish MCP from direct API calls and model function-calling schemas.</p></section>
<section class="lesson-section"><h3>Concept</h3><p>The Model Context Protocol (MCP) is a protocol for connecting AI applications with servers that expose capabilities such as tools, resources, and prompts. A direct API is an application-specific interface; function calling is a model interaction pattern and may be used inside an MCP-enabled host.</p></section>
<section class="lesson-section"><h3>Example</h3><p>A host can discover an MCP server&#39;s tools, while a separate model call decides whether to propose one of those tools.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Classify four integration diagrams as direct API, function calling, MCP, or combinations and explain the protocol boundary.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>MCP standardizes a connection protocol; it is not itself a model or a generic synonym for APIs.</p></section>' WHERE id = '80f74c3a-492f-4efe-aaba-4ae628c9721a' AND module_id = 'eb427a53-1c31-4c0b-91fd-bfdfdfb806af' AND title = 'MCP and Adjacent Integration Patterns' AND lesson_order = 2 AND content = '<section class="lesson-section"><h3>Story</h3><p>A desktop assistant can explain a spreadsheet formula but cannot inspect the user&#39;s authorized workbook until connected to a capability.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>Identify what the model can infer and what requires an external, permissioned tool or resource.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Distinguish MCP from direct API calls and model function-calling schemas.</p></section>
<section class="lesson-section"><h3>Concept</h3><p>MCP is a protocol for connecting AI applications with servers that expose capabilities such as tools, resources, and prompts. A direct API is an application-specific interface; function calling is a model interaction pattern and may be used inside an MCP-enabled host.</p></section>
<section class="lesson-section"><h3>Example</h3><p>A host can discover an MCP server&#39;s tools, while a separate model call decides whether to propose one of those tools.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Classify four integration diagrams as direct API, function calling, MCP, or combinations and explain the protocol boundary.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>MCP standardizes a connection protocol; it is not itself a model or a generic synonym for APIs.</p></section>';
COMMIT;
-- Rollback template for the modern-course clarification:
-- UPDATE public.courses SET description = 'Design, test, and improve prompts and multi-step LLM workflows for useful, verifiable outcomes.' WHERE id = 'prompt_engineering' AND description = 'Design, test, and improve prompts and multi-step large language model (LLM) workflows for useful, verifiable outcomes.';
-- UPDATE public.courses SET description = 'Build LLM applications using model APIs, structured outputs, embeddings, conversation state, and practical reliability controls.' WHERE id = 'generative_ai_llm' AND description = 'Build large language model (LLM) applications using model APIs, structured outputs, embeddings, conversation state, and practical reliability controls.';
-- UPDATE public.courses SET description = 'Connect AI applications to external capabilities using MCP concepts, server-provided tools/resources, and explicit permissions.' WHERE id = 'mcp_tool_connected_ai' AND description = 'Connect AI applications to external capabilities using the Model Context Protocol (MCP), server-provided tools/resources, and explicit permissions.';
-- UPDATE public.lessons SET content = '<section class="lesson-section"><h3>Story</h3><p>A desktop assistant can explain a spreadsheet formula but cannot inspect the user&#39;s authorized workbook until connected to a capability.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>Identify what the model can infer and what requires an external, permissioned tool or resource.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Distinguish MCP from direct API calls and model function-calling schemas.</p></section>
<section class="lesson-section"><h3>Concept</h3><p>MCP is a protocol for connecting AI applications with servers that expose capabilities such as tools, resources, and prompts. A direct API is an application-specific interface; function calling is a model interaction pattern and may be used inside an MCP-enabled host.</p></section>
<section class="lesson-section"><h3>Example</h3><p>A host can discover an MCP server&#39;s tools, while a separate model call decides whether to propose one of those tools.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Classify four integration diagrams as direct API, function calling, MCP, or combinations and explain the protocol boundary.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>MCP standardizes a connection protocol; it is not itself a model or a generic synonym for APIs.</p></section>' WHERE id = '80f74c3a-492f-4efe-aaba-4ae628c9721a' AND module_id = 'eb427a53-1c31-4c0b-91fd-bfdfdfb806af' AND title = 'MCP and Adjacent Integration Patterns' AND lesson_order = 2 AND content = '<section class="lesson-section"><h3>Story</h3><p>A desktop assistant can explain a spreadsheet formula but cannot inspect the user&#39;s authorized workbook until connected to a capability.</p></section>
<section class="lesson-section"><h3>Discovery</h3><p>Identify what the model can infer and what requires an external, permissioned tool or resource.</p></section>
<section class="lesson-section"><h3>Learning Objective</h3><p>Distinguish MCP from direct API calls and model function-calling schemas.</p></section>
<section class="lesson-section"><h3>Concept</h3><p>The Model Context Protocol (MCP) is a protocol for connecting AI applications with servers that expose capabilities such as tools, resources, and prompts. A direct API is an application-specific interface; function calling is a model interaction pattern and may be used inside an MCP-enabled host.</p></section>
<section class="lesson-section"><h3>Example</h3><p>A host can discover an MCP server&#39;s tools, while a separate model call decides whether to propose one of those tools.</p></section>
<section class="lesson-section"><h3>Challenge</h3><p>Classify four integration diagrams as direct API, function calling, MCP, or combinations and explain the protocol boundary.</p></section>
<section class="lesson-section"><h3>Takeaway</h3><p>MCP standardizes a connection protocol; it is not itself a model or a generic synonym for APIs.</p></section>';
